apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: diff
  name: diff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diff
  template:
    metadata:
      labels:
        app: diff
    spec:
      containers:
        - image: "public.ecr.aws/z8c2k6d0/diff:{{ .Chart.AppVersion }}"
          name: diff
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
